# Makefile.cfg for Quest compiled using the DJGPP package
# ( http://www.delorie.com/djgpp/ )

CC		= gcc
CXX		= gcc
CFLAGS		= -g -Wall -O2
CXXFLAGS	= -g -Wall -O2
MAKE		= make
DO_DJGPP	= yes
TARGETS		= quest.exe
